/**
 * Writes the Supabase Auth email templates to email-templates/*.html.
 *   npm run build:emails
 * Then paste each file's body into Dashboard → Authentication → Emails →
 * Templates, keeping the subject printed below.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { buildAuthTemplates } from "../lib/email/auth-templates";

const outDir = join(process.cwd(), "email-templates");
mkdirSync(outDir, { recursive: true });

for (const t of buildAuthTemplates()) {
  const banner = `<!--\n  Supabase → Authentication → Emails → Templates → ${t.key}\n  Subject: ${t.subject}\n  Generated by scripts/build-auth-emails.ts — edit lib/email/auth-templates.ts, not this file.\n-->\n`;
  writeFileSync(join(outDir, t.file), banner + t.rendered.html, "utf8");
  console.log(`${t.file}  (subject: ${t.subject})`);
}
